version: 2.1
orbs:
  node: circleci/node@3.0.0
  heroku: circleci/heroku@1.2.3 # Invoke the Heroku orb

workflows:
  node-tests:
    jobs:
      - node/test
      - deploy
jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          command: >
            echo "The command above installs Heroku, the command below deploys.
            What you do inbetween is up to you!"
      - heroku/deploy-via-git
          requires:
            - node/test
          # filters:
          #   branches:
          #     only: sequential-branch-filter