version: 2.1
orbs:
  node: circleci/node@3.0.0
  heroku: circleci/heroku@1.2.3 # Invoke the Heroku orb

workflows:
  node-tests:
    jobs:
      - node/test
      - deploy
          requires:
            - node/test
jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
          # filters:
          #   branches:
          #     only: sequential-branch-filter