version: 2.1
orbs:
  node: circleci/node@3.0.0
  heroku: circleci/heroku@1.2.3 # Invoke the Heroku orb

workflows:
  node-tests:
    jobs:
      - node/test
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          # filters:
          #   branches:
          #     only: sequential-branch-filter