version: 2.1
orbs:
  node: circleci/node@3.0.0
  heroku: circleci/heroku@1.2.3 # Invoke the Heroku orb
jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git

workflows:
  node-test-deploy:
    jobs:
      - node/test:
        filters:
            branches:
              only: master
      - deploy:
          requires:
            - node/test
          filters:
            branches:
              only: master
